#LAMP stack docker-compose using
#cusom PHP apache with mysqli, mariadb, and phpmyadmin

version: '3.7'

services:
  php-httpd:
    build: ./php
    ports:
      - 8000:80
    volumes:
      - './www:/var/www/html'

  mariadb:
    image: mariadb:10.5.2
    volumes:
      - mariadb-volume:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
      MYSQL_ROOT_PASSWORD: 'rootpwd'
      MYSQL_USER: 'testuser'
      MYSQL_PASSWORD: 'testpassword'
      MYSQL_DATABASE: 'testdb'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - 'mariadb:db'
    ports:
      - 8081:80

volumes:
  mariadb-volume:
