version: '3.7'

services:
  php-httpd:
    build: ./php
    ports:
      - 8000:80
    volumes:
      - './www:/var/www/html'

  mysql:
    build: ./mysql
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
      MYSQL_ROOT_PASSWORD: 'root'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - 'mysql:db'
    ports:
      - 8081:80

volumes:
  mysql-volume:
